
sensor:
  - platform: mqtt
    name: c4w1
    #friendly_name: "Włącznik Garderoba"
    state_topic: "info/c4/c4w1"
    unit_of_measurement: 'stan'
    value_template: >
      {% if value_json.isDblC==1 %}
        DblClicked_{{ value_json.btnSt }}
      {% else %}
        {% if value_json.isC==1 %}
          Clicked_{{ value_json.btnSt }}
        {% else %}
          {% if value_json.isSw==1 %}
            Switched_{{ value_json.btnSt }}
          {% else %}
            {{ value_json.btnSt }}
          {% endif %}
        {% endif %} 
      {% endif %}

  - platform: mqtt
    name: c4w2
      #friendly_name: "Włącznik Pralnia"
    state_topic: "info/c4/c4w2"
    unit_of_measurement: 'stan'
    value_template: >
        {% if value_json.isDblC==1 %}
          DblClicked_{{ value_json.btnSt }}
        {% else %}
          {% if value_json.isC==1 %}
            Clicked_{{ value_json.btnSt }}
          {% else %}
            {% if value_json.isSw==1 %}
              Switched_{{ value_json.btnSt }}
            {% else %}
              {{ value_json.btnSt }}
            {% endif %}
          {% endif %} 
        {% endif %}

  - platform: mqtt
    name: c4w3
        #friendly_name: "Włącznik Łazienka"
    state_topic: "info/c4/c4w3"
    unit_of_measurement: 'stan'
    value_template: >
          {% if value_json.isDblC==1 %}
            DblClicked_{{ value_json.btnSt }}
          {% else %}
            {% if value_json.isC==1 %}
              Clicked_{{ value_json.btnSt }}
            {% else %}
              {% if value_json.isSw==1 %}
                Switched_{{ value_json.btnSt }}
              {% else %}
                {{ value_json.btnSt }}
              {% endif %}
            {% endif %} 
          {% endif %}
      
  - platform: mqtt
    name: c4w4
         #friendly_name: "Włącznik Łazienka kinkiet"
    state_topic: "info/c4/c4w4"
    unit_of_measurement: 'stan'
    value_template: >
            {% if value_json.isDblC==1 %}
              DblClicked_{{ value_json.btnSt }}
            {% else %}
              {% if value_json.isC==1 %}
                Clicked_{{ value_json.btnSt }}
              {% else %}
                {% if value_json.isSw==1 %}
                  Switched_{{ value_json.btnSt }}
                {% else %}
                  {{ value_json.btnSt }}
                {% endif %}
              {% endif %} 
            {% endif %}
      
  - platform: mqtt
    name: c4w5
            #friendly_name: "Włącznik sypialnia"
    state_topic: "info/c4/c4w5"
    unit_of_measurement: 'stan'
    value_template: >
              {% if value_json.isDblC==1 %}
                DblClicked_{{ value_json.btnSt }}
              {% else %}
                {% if value_json.isC==1 %}
                  Clicked_{{ value_json.btnSt }}
                {% else %}
                  {% if value_json.isSw==1 %}
                    Switched_{{ value_json.btnSt }}
                  {% else %}
                    {{ value_json.btnSt }}
                  {% endif %}
                {% endif %} 
              {% endif %}
    
  