
#{"name":"c4s1","dev":"c4s1","v":0,"state":"ON","isFad":0,"aimV":0,"isW8t4Chng":1,"futSt":100,"ttc":7.0}
sensor:
  ######################## PIR #########################################
  - platform: mqtt
    name: c4p1 #friendly_name: "PIR Garderoba"
    state_topic: "info/c4/c4p1"
    unit_of_measurement: 'PIR'
    value_template: "{% if value_json.isSw==1 and value_json.btnSt=='r'%} Ruch {% else %} Cisza {% endif %}"
  
  - platform: mqtt
    name: c4p2 #friendly_name: "PIR Garderoba"
    state_topic: "info/c4/c4p2"
    unit_of_measurement: 'PIR'
    value_template: "{% if value_json.isSw==1 and value_json.btnSt=='r'%} Ruch {% else %} Cisza {% endif %}"
  
  - platform: mqtt
    name: c4p3 #friendly_name: "PIR Garderoba"
    state_topic: "info/c4/c4p3"
    unit_of_measurement: 'PIR'
    value_template: "{% if value_json.isSw==1 and value_json.btnSt=='r'%} Ruch {% else %} Cisza {% endif %}"
  
  - platform: mqtt
    name: c4p4 #friendly_name: "PIR Garderoba"
    state_topic: "info/c4/c4p4"
    unit_of_measurement: 'PIR'
    value_template: "{% if value_json.isSw==1 and value_json.btnSt=='r'%} Ruch {% else %} Cisza {% endif %}"
  
  - platform: mqtt
    name: c4p5 #friendly_name: "PIR Garderoba"
    state_topic: "info/c4/c4p5"
    unit_of_measurement: 'PIR'
    value_template: "{% if value_json.isSw==1 and value_json.btnSt=='r'%} Ruch {% else %} Cisza {% endif %}"
  