homeassistant:
  packages: !include_dir_named packagesC4
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

sonoff:
    username: !secret SonoffUsr
    password: !secret Sonoffpwrd

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
